// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ocs.Database.Context;

#nullable disable

namespace Ocs.Database.Migrations
{
    [DbContext(typeof(OcsContext))]
    [Migration("20230501201604_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ocs.Domain.Models.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Line");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aff3afa8-65df-4b6f-89ed-a5f46b18a61a")
                        },
                        new
                        {
                            Id = new Guid("ce24dfd7-b167-44c3-8afd-159bec9e6e2e")
                        },
                        new
                        {
                            Id = new Guid("93e297f9-d684-41b9-b6c4-b52581acebd8")
                        },
                        new
                        {
                            Id = new Guid("22698cf8-8957-47b6-aafd-6755f11add5f")
                        },
                        new
                        {
                            Id = new Guid("d7b56112-5411-4b1c-8163-95f654f8f5cf")
                        },
                        new
                        {
                            Id = new Guid("20135180-226b-43bf-af3c-8dca53427587")
                        },
                        new
                        {
                            Id = new Guid("c6b67aac-5954-469e-acd1-ad7a384d1875")
                        },
                        new
                        {
                            Id = new Guid("106ab175-294f-4364-ad0f-31c3c541fc11")
                        },
                        new
                        {
                            Id = new Guid("b79b3456-4f33-4d5d-a9e4-7b2fa8ed6e54")
                        },
                        new
                        {
                            Id = new Guid("3c90ba9b-0557-4db3-8733-7b0f645c65d0")
                        },
                        new
                        {
                            Id = new Guid("d28d44e1-5e12-4413-b773-56d16da146d2")
                        },
                        new
                        {
                            Id = new Guid("df359c88-4541-433b-bc2a-3a2cb305e352")
                        },
                        new
                        {
                            Id = new Guid("0f2c07fb-29ed-4c66-a5c3-a9d4256002d3")
                        },
                        new
                        {
                            Id = new Guid("56bc261f-cf87-483a-909c-3e333470fd42")
                        },
                        new
                        {
                            Id = new Guid("61abd1c8-9fd0-4048-8bf8-f31ed476a52b")
                        },
                        new
                        {
                            Id = new Guid("b9f76b9f-87fa-4737-ab57-15838554ba80")
                        },
                        new
                        {
                            Id = new Guid("15e21011-4105-4bf5-b639-13398b637f68")
                        },
                        new
                        {
                            Id = new Guid("458d55f7-bd4a-457c-bb19-904e8cfc7dcd")
                        },
                        new
                        {
                            Id = new Guid("242f1809-8378-4312-91fd-3d9436e212a7")
                        },
                        new
                        {
                            Id = new Guid("dbba1488-15a3-48f0-a403-9d3846bf310b")
                        },
                        new
                        {
                            Id = new Guid("8b34735d-8189-45b4-aadc-fb9d6e07a703")
                        },
                        new
                        {
                            Id = new Guid("2faae84f-c8eb-484d-a524-b5471fcf6a53")
                        },
                        new
                        {
                            Id = new Guid("67a614da-0127-437b-8b0d-f1d76ac3038e")
                        },
                        new
                        {
                            Id = new Guid("a32b1bbb-7f39-4c68-9a8a-90ab058a2e86")
                        },
                        new
                        {
                            Id = new Guid("626be9f4-63e6-403a-afbe-1455923a8bc2")
                        },
                        new
                        {
                            Id = new Guid("63c03215-28ed-4edc-a6c6-0ecf5b6ecaa8")
                        },
                        new
                        {
                            Id = new Guid("8db7735a-bb82-4055-bbe4-4686bd64e07e")
                        },
                        new
                        {
                            Id = new Guid("e0fdcf76-17c8-4ed0-8d1f-078e0783a117")
                        },
                        new
                        {
                            Id = new Guid("2ce73928-8537-407c-9301-d4357c1fa0d2")
                        },
                        new
                        {
                            Id = new Guid("cdfdb77b-5638-4524-a99e-2cfbb27fa5ef")
                        },
                        new
                        {
                            Id = new Guid("d7df1797-e88e-4e02-95d0-006987426e95")
                        },
                        new
                        {
                            Id = new Guid("de9544ae-7f20-4333-81e0-2d9d035dd0df")
                        },
                        new
                        {
                            Id = new Guid("0ce5af31-68a7-4c29-92f5-9546c944144f")
                        },
                        new
                        {
                            Id = new Guid("82963531-08b4-42bc-8ca5-2b63217b907b")
                        },
                        new
                        {
                            Id = new Guid("bde84c87-6f9f-4899-83a6-5d9c45541342")
                        },
                        new
                        {
                            Id = new Guid("94335d2b-933b-47db-8d1e-8b4f1b868011")
                        },
                        new
                        {
                            Id = new Guid("7032c6f6-f0e6-4f9d-a312-7103a705f8f4")
                        },
                        new
                        {
                            Id = new Guid("a69ad73a-80b3-4232-b888-96cced0a28f5")
                        },
                        new
                        {
                            Id = new Guid("110da4a4-93f4-46c1-9f78-cfc29d1dd9b9")
                        },
                        new
                        {
                            Id = new Guid("fcf750cf-a001-4a76-a25d-554ee18e0dd1")
                        },
                        new
                        {
                            Id = new Guid("a734c5a6-c0a2-491e-8ff4-3709b3e87d62")
                        },
                        new
                        {
                            Id = new Guid("009b05ff-bd04-4168-ac70-17432900316d")
                        },
                        new
                        {
                            Id = new Guid("88200354-7139-4e79-aa8f-0c0f6b52ab1b")
                        },
                        new
                        {
                            Id = new Guid("bae680f2-4836-4cb0-880e-7cb3c6678ea3")
                        },
                        new
                        {
                            Id = new Guid("791958aa-29d8-4bab-bee1-9941d86b9e8e")
                        },
                        new
                        {
                            Id = new Guid("1f0abea1-2039-474e-b2c4-2b2f1032382a")
                        },
                        new
                        {
                            Id = new Guid("f8744b5b-e6ad-4727-9313-ccf899d3b13e")
                        },
                        new
                        {
                            Id = new Guid("2aaab396-0c79-486b-a7f9-85e79858abe7")
                        },
                        new
                        {
                            Id = new Guid("ff3541f9-4a1a-41c2-8281-dee2c72b683e")
                        },
                        new
                        {
                            Id = new Guid("bf72d2bd-34d8-416d-9e02-6ec1fc83f14a")
                        });
                });

            modelBuilder.Entity("Ocs.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2023, 5, 1, 20, 16, 4, 294, DateTimeKind.Utc).AddTicks(1137));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ocs.Domain.Models.OrderLines", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("LineId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Ocs.Domain.Models.OrderLines", b =>
                {
                    b.HasOne("Ocs.Domain.Models.Line", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ocs.Domain.Models.Order", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ocs.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
